# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  box_arch = if(RUBY_PLATFORM =~ /64/) then "x86_64" else "i386" end
  is_windows = (RUBY_PLATFORM =~ /mswin|mingw|cygwin/)
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
   config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
   config.vm.network :forwarded_port, guest: 8000, host: 8000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.synced_folder "../../", "/Vagrant"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
     if !is_windows then
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4", "--uartmode1", "server", "/tmp/sim_ttyS0"]
     else
       vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4", "--uartmode1", "server", "\\\\.\\pipe\\sim_ttyS0"]
     end
   end

   config.vm.provision :shell,
       :inline => "sudo adduser vagrant dialout"

   config.vm.provision :puppet, :module_path => "../modules" do |puppet|
     puppet.manifests_path = "../manifests"
     puppet.manifest_file  = "default.pp"
     puppet.options = "--verbose --debug"
   end

  
end
